print("-"*60)
print("-"*60)
print()
print("Welcome to addtion Program ".center(60))
print()
x = int(input("Enter x : ".center(60).rstrip()))
y = int(input("ENter y : ".center(60).rstrip()))
print()
print(f"x = {x}".center(60))
print(f"y = {y}".center(60))
print(f"{x} + {y} = {x+y}".center(60))
print()
print("Thanks for using this program".center(60))
print()
print("-"*60)
print("-"*60)
